### ISSUE TITLE
Headers are read-only, response has already started

### ISSUE THREAD

**Issue by rachavz** [integrativesoft/lara#102]
Hi, 
When debug lara in aspnetcore web project I have the next fail : Headers are read-only, response has already started

trace in the file MiddlewareCommon.cs function 

```
public static async Task WriteBuffer(HttpContext http, byte[] buffer)
        {
            try
            {
                await http.Response.Body.WriteAsync(buffer.AsMemory(0, buffer.Length));
                http.Response.ContentLength = buffer.Length;
            }
            catch (Exception ex)
            {
                throw;   //here put break point
            }
        }
```

**Comment by pablocar80** [comment]
The issue is that if you modify the headers, then that line crashes?

**Comment by pablocar80** [comment]
Do you have any more information to reproduce the issue?

**Comment by rachavz** [comment]
Only show the message every time, I made a simple web project in 

https://github.com/rChavz/lara/tree/master/src/SampleWeb

but when run show the message

**Comment by rachavz** [comment]
if yo have time please check this file 

https://github.com/rChavz/lara/blob/master/src/SampleWeb/Pages/CounterPageJson.cs

if you like, we can make some changes for more easy integration

**Comment by pablocar80** [comment]
I cloned the repo and had a few compile errors, after fixing them, I am able to execute and run the following:

![image](https://user-images.githubusercontent.com/36197603/101287696-7b2cab80-37b7-11eb-86e1-314dd75d7b75.png)

I did not get any errors when clicking.... how do I get the error to show?

**Comment by pablocar80** [comment]
@rChavz do you have any other information on this? Thanks!

**Comment by rachavz** [comment]
what you think about write the ui in json?

**Comment by pablocar80** [comment]
Were you able to fix the issue? I could not reproduce it in the sample repo you linked.

About the json question, looks like an interesting approach. There is no syntax checking during compile time. Have you tried using the LaraBuilder class, and if yes, how was your experience with it?

**Comment by rachavz** [comment]
the message error occurs when debug in netcore app, when run in IISExpress does not appear

**Comment by pablocar80** [comment]
Ok I was able to reproduce the error, looking into it

**Comment by pablocar80** [comment]
the latest version published on nuget fixes this issue, thank you very much for reporting it @rChavz
