### ISSUE TITLE
Session Handling not working in 'default' hosting mode?

### ISSUE THREAD

**Issue by Seji64** [integrativesoft/lara#96]
Hi,
first of all - absolutely great project!

I am currently 'playing' a bit with lara and trying to set up a login page. But somehow 'LaraUI.Page.Session' is not working as expectected (is null). When i switch to "BrowserApp" Mode all is working fine. Is this by design or i am doing something wrong?

PS: Could you provide a Login Site sample? cause i think how i handle the login is not very nice....

**Comment by pablocar80** [comment]
Hello @Seji64 , thank you!
I tried to modify the mode for the sample application, and I could still see the Session, when executing code within an event (i.e. click of a button).
Would you mind pasting code or uploading a repository with the issue, to help me reproduce the error?

**Comment by Seji64** [comment]
hi and sorry for the late response. The error/bug was my own failure. The access to the session is working fine. I have another issue, but i will open a new one for that.
