### ISSUE TITLE
Publishing File Issue

### ISSUE THREAD

**Issue by Seji64** [integrativesoft/lara#97]
Hi again,

i tried to publish a JS File. But i am getting the error, that the file cannot be found.

![grafik](https://user-images.githubusercontent.com/19726119/85175519-ede0b380-b277-11ea-96f9-0388d8c21688.png)

```
 class Program
    {
        static async Task Main()
        {
            using var app = new Application();
            await app.Start(new StartServerOptions
            {
                Mode = ApplicationMode.Default,
                PublishAssembliesOnStart = true,
                Port = 1337
            });


            var bytes = File.ReadAllBytes("JS\\Helper.js");
            var content = new StaticContent(bytes, ContentTypes.ApplicationJavascript);
            LaraUI.Publish("/helper.js", content);

            await app.WaitForShutdown();
        }
    }
```

I am doing something wrong?

**Comment by pablocar80** [comment]
I’ll take a look at it tonight when I get to the computer. In the meantime, is there an app.Publish method you can use, instead of calling LaraUI.Publish?

**Comment by Seji64** [comment]
Ahh, this works perfectly. You should update your Documentation cause the example there is using `LaraUI.Publish`

Thanks for your help anyway!

**Comment by pablocar80** [comment]
Will do, let’s leave this issue open until I update it

**Comment by pablocar80** [comment]
Updated documentation. Also considering deprecating static methods to avoid confusion.
